### ISSUE TITLE
Firebase not receiving Data

### ISSUE THREAD

**Issue by sw1mm3r202** [birdwell/Madden-Companion-Exporter#11]
I shot you an email earlier and hoping to see if you could help. I am having a similar issue where firebase is not receiving the data. The exporter is sending the data correctly to herokuapp but it isn't writing to the firebase. Any help you could offer would be great, I really appreciate it.

**Comment by Zero2Cool** [comment]
Are you receiving any error in your herokuapp logs?

**Comment by sw1mm3r202** [comment]
I don't believe so. Although I'm not sure I am looking at herokuapp logs correctly. First time using it.

**Comment by Zero2Cool** [comment]
Yeah, nothing is sticking out there.  Are you able to view your database via the console at firebase? https://console.firebase.google.com/u/0/  ??

**Comment by sw1mm3r202** [comment]
I made it public, if you don't mind looking at it. I appreciate the help. I am able to view the database and am able to read and write into it in firebase and have it set up to allow reading and writing. Here is the header to my .JS file - I am just not sure where the disconnect is:

var express = require('express');
var bodyParser = require('body-parser');
var admin = require("firebase-admin");

const app = express();

// TODO: Enter the path to your service account json file
// Need help with this step go here: https://firebase.google.com/docs/admin/setup
const serviceAccount = require("./ggcfmkey.json");

// TODO: Enter your database url from firebase
admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  databaseURL: "https://gg-cfm-b273a.firebaseio.com"
});

**Comment by Zero2Cool** [comment]
I'm at work so can't do a deep dive, but https://gg-cfm-b273a.firebaseio.com/.json  I get permission denied. This could be expected though as I'm viewing a Public or Guest.  I noticed you have two keys.  Are you sure the correct one is setup?   I ran into an issue my first time and ended up deleting my "project" on firebase, opened a new one and went step by step.  Then it worked.  I'll have to come back to this and check because it looks like this should be good. Only thing I don't know for sure is if you have the repo from GitHub connected to HeroKu?

Under the Deploy tab...
![image](https://user-images.githubusercontent.com/5612416/53498925-f0107480-3a6c-11e9-85b2-37b340ecb040.png)

**Comment by sw1mm3r202** [comment]
Hmm I have tried that multiple times... I guess I can try again with a new project. As far as the keys, after it wasn't working the first time I wanted to see if the "-" within the name was causing issues so I created a new key to setup the project without any irregular character in the name. As far as Heroku, yes it is connected and I manually deployed the main branch. I just don't understand where the data is getting exported to. when going to the actual app on heroku, I get "Cannot get /" which I guess is to be expected because I don't have an INDEX.html file.

**Comment by sw1mm3r202** [comment]
Looking through your project @Zero2Cool, I noticed your app.js is a couple lines longer. Was that manual modifications or directly from the project you forked?

**Comment by Zero2Cool** [comment]
I modified mine a little bit. I think I removed the platform and I think I added a user string.

**Comment by sw1mm3r202** [comment]
@Zero2Cool when I try that I get an export fail as url is 404, I am guessing because of the platform removal trying to post to the full url: url.com/xbox/4052707/standings

**Comment by Zero2Cool** [comment]
did you pass a parameter after your URL?  whatever your .  xxx.herokuapp.com url is, you have to pass a variable through.  I create a unique five character string for mine.

**Comment by Zero2Cool** [comment]
So, I just copied the app.js from Josh's repo, and put my key and stuff in there, export says success, but ... nothing in my database.

**Comment by sw1mm3r202** [comment]
when you say pass a parameter, do you mean javascript code the parameter, or Heroku config Var, or establish the parameter in the app?

And yeah that is the issue I am having. Everythinig says it works but I don't see anything in the database.

**Comment by Zero2Cool** [comment]
for my app.js ...  I have the main URL, but since my site is used by multiple leagues i needed multiple URL's, so i added a parameter at the end so my database would have an extra node level. 

Do you see Madden and Test? That's because my URL was like  https://my.herokuapp.com/Madden and https://my.herokuapp.com/Test

![image](https://user-images.githubusercontent.com/5612416/53516157-4099c900-3a91-11e9-8228-108e1210d1e4.png)

No worries about being new, I am new to this too. @birdwell  probably has my email blacklisted due to all my questions! haha

**Comment by sw1mm3r202** [comment]
@Zero2Cool i can't believe I missed it. but omfg it worked. Is it cool if I use your app.js for my own league?

**Comment by Zero2Cool** [comment]
Absolutely you can use my app.js, just put your own firebase information in there :P

**Comment by sw1mm3r202** [comment]
yeah no worries I was at least smart enough not to export to your database/key. I kept my info for it haha

**Comment by Zero2Cool** [comment]
Glad you got it working! You gonna make a website with your information or what is your plan? (Always curious how people use the data!!!)  

Also, something else you might find interesting is @keylimesoda repo https://github.com/keylimesoda/MaddenToCSV   give it a look.  He's okay, I mean, for a Saints fan.

**Comment by sw1mm3r202** [comment]
haha I saw that, but yeah I have more experience in website building than javascript modelling. I can read javascript but writing it I am not quite as fluent. And yeah, my friends and I have a madden league that goes from madden to madden (17,18,19 etc) and they have reddit, discord, google sheets, google docs, and questionairres, daddyleagues (I hope that isn't your website), and it is getting really hectic to keep track of it all so I am creating a website to basically connect to firebase and go from there so everybody has a centralized place for info haha.

Again I really appreciate all the time and help you gave to get this working for me.

**Comment by Zero2Cool** [comment]
Oh, I also removed leagueId, you might wanna add that back in for your usage.  I removed it because I'm creating my own unique league id as I didn't trust that the exporter kept all leagueI'd's unique.

**Comment by Zero2Cool** [comment]
Nah, my website isn't daddy leagues, mine is www.cfmstats.com

**Comment by Zero2Cool** [comment]
@sw1mm3r202 if your issue is closed, can you close this?

**Comment by sw1mm3r202** [comment]
Thanks again!

**Comment by birdwell** [comment]
You guys are having a ton of fun without me. Sorry I couldn't join in!

**Comment by keylimesoda** [comment]
Hey, I just learned it from copying your code Josh ;)

Hope post-college work-life is treating you well. We're still hiring at
Microsoft when you're ready for a change.
