### ISSUE TITLE
Madden 20

### ISSUE THREAD

**Issue by Zero2Cool** [birdwell/Madden-Companion-Exporter#12]
Have you had any beta tester toss export data through your tool yet?

**Comment by Zero2Cool** [comment]
I'll just have to do it myself when my copy arrives in the mail then! :P

**Comment by birdwell** [comment]
It still works. I used it for the Madden Fantasy.

**Comment by Zero2Cool** [comment]
I was hoping for some new ratings, but it looks like Madden 19 export from the first glance of it.
