### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by TopL0ader** [birdwell/Madden-Companion-Exporter#16]
Hi there,

I have followed the instructions several times over and I have been unable to sync any Madden 20 data from the Companion app to my database. I am at my wits end and I have no clue as to what I am missing. I would be eternally grateful if you could look over the repository and confirm my code is correct?

Thanks in advance

**Comment by Zero2Cool** [comment]
What error message are you getting?  

Also, there was a pull request merge just completed that includes the Free Agents.

**Comment by TopL0ader** [comment]
think i have now sorted it thank you, I have spent so many hours on this.... Appreciate your reply

**Comment by Zero2Cool** [comment]
Glad you got it figured out!  It sure can be a pain in the a$$, but once you get it, you can do things like this at www.cfmstats.com all thanks to Josh!

**Comment by TopL0ader** [comment]
Again, thanks.

That's my plan, we have eight leagues with a site I'll not mention and paying some decent money to the site. If I can create a basic one on our website then we'll be quids in and happy.
Thanks for your time, now it's time for me to learn how to pull the data into html etc

**Comment by Zero2Cool** [comment]
Check out https://gamerhuddle.com, they are free. Derek is pretty responsive to his users so if you want a feature, he will likely add it.  Mine is also free, but mine isn't too mobile friendly because I have a lot of large data sets, lol.

**Comment by TopL0ader** [comment]
Seen both bud, and like all three.

We have a test league on gamerhuddle.com, but it would be nice to be self sufficient. 

Plus I enjoy the challenge

**Comment by TopL0ader** [comment]
We use the same html template as gamerhuddle.com,...

**Comment by TopL0ader** [comment]
https://maddenpfl.com

**Comment by Zero2Cool** [comment]
> Seen both bud, and like all three.
> 
> We have a test league on gamerhuddle.com, but it would be nice to be self sufficient.
> 
> Plus I enjoy the challenge

The whole self-sufficient thing is why I went on my own as well. :-)  Plus, I always like adding new things and historical data. 

Nice looking site, can't wait to see it when you get your data flowing.
