### ISSUE TITLE
Assistance

### ISSUE THREAD

**Issue by TopL0ader** [birdwell/Madden-Companion-Exporter#17]
@Zero2Cool Big ask.... Any chance I could have a copy of your startup html/js to get the firebase data into a website.

**Comment by Zero2Cool** [comment]
You'll need a ASP.NET Host and SQL Server database. I'm exporting the data to firebase, then I have a tool that manipulates it into SQL database.

**Comment by TopL0ader** [comment]
Thanks buddy,

I figured it out and posted teamName, userName and teamOvr into a table.

Working hard learning on the fly
