### ISSUE TITLE
Firebase not receiving updated data

### ISSUE THREAD

**Issue by timanity** [birdwell/Madden-Companion-Exporter#23]
Hi!

I have an issue with updating the data in firebase. No issues in creating a new branch inside firebase but updating a current one is the issue. 

This is what it says inside the logs on Heroku:

_"2021-06-23T22:54:27.508487+00:00 app[web.1]: [2021-06-23T22:54:27.508Z]  @firebase/database: FIREBASE WARNING: Passing an Array to Firebase.update() is deprecated. Use set() if you want to overwrite the existing data, or an Object with integer keys if you really do want to only update some of the children."_

Do you know what the issue might be?

Thanks,
Timmy

**Comment by moniqx4** [comment]
In the app.js, look for .update being used, and change it to .set, for example:

teams.forEach(team => {
            const teamRef = ref.child(`data/leagues/${platform}/${leagueId}/teams/${team.teamId}`);
            **teamRef.set(team);**
        });

Firebase made a change to the command for updating data, and that message is letting you know that and what it has been  changed to

**Comment by KevinDuganJr** [comment]
Closing this as commit fdbd8a2894baf19a7447f4c7cfaef6ab111ee0ee should resolve it.
