### ISSUE TITLE
Question :  Weekly Stats

### ISSUE THREAD

**Issue by Zero2Cool** [birdwell/Madden-Companion-Exporter#5]
I've started from scratch two separate times. New Fork, New HeroUK app, New Firebase ... etc .. and I can't get the Weekly Stats to work. I keep this error in the attached image. 

Edit, all three phases work flawlessly from https://maddenexporter.herokuapp.com/myusername

![screenshot_20170515-202037](https://cloud.githubusercontent.com/assets/5612416/26085804/5b8294aa-39ac-11e7-8c6f-cadf3fd49ed8.png)

**Comment by birdwell** [comment]
I left out a helper function from my last commit. I updated it this morning. Let me know if this resolves your issue.

**Comment by Zero2Cool** [comment]
It looks like we're golden here thank you 
![screenshot_20170525-055253](https://cloud.githubusercontent.com/assets/5612416/26447531/860cc722-410e-11e7-852e-39f0b4ffac6e.png)

**Comment by birdwell** [comment]
Sweet! 👍

**Comment by Zero2Cool** [comment]
I just confirmed the Weekly Stats are in the Firebase database as well.
