### ISSUE TITLE
How to Import into a Laravel/MySQL Project?

### ISSUE THREAD

**Issue by furious-bez** [birdwell/Madden-Companion-Exporter#7]
I have forked this project in the hopes of using it in Laravel project using a MySQL database.

I have already succeeded with a manual download of the JSON created at the https://maddenexporter.herokuapp.com site and imported data into a MySQL database.  

What I need to know is if using this repository would require my Laravel Project to bind to the firebase DB or if it can be modified to provide the json which can be read into the Laravel Project to to process into MySQL.

P.S. - I'm an intermediate level developer.
Included a snapshot of how I'm using the Madden 18 data so far.
![sample-of-m18-data](https://user-images.githubusercontent.com/1278361/29847709-f3911348-8cd1-11e7-9371-d6ee19a49014.PNG)

**Comment by Zero2Cool** [comment]
That looks really nice! Where did you get the profile images? 

What I did for my site was create a JSON object and loop through each one and execute a insert if new, and update if existing record.  www.kevinduganjr.com if you're curious to see what it looks like.

**Comment by furious-bez** [comment]
That is exactly what I did.  I import and extract the zip file and process each of the 3 json files.
I too use updateOrCreate via Eloquent Model.  What I wanted to do was be able to export data using the Madden NFL 18 companion app and run the Updates without using a third-party site, download and re-upload into production server.

The profile images are available at EA's website.

**Comment by Zero2Cool** [comment]
I'm using SQL and C#. I read the JSON file, loop through it and execute my stored procedures that I wrote to update or insert. It would be nice to have something periodically check the JSON file, and then do a sync and then wipe the firebase clean. But, the update process I have is pretty simple. I just click a button and it does it.

**Comment by furious-bez** [comment]
Yes, but how are you acquiring the JSON is what I need to determine.
As I stated previously, I have to download the ZIP file locally, re-upload to server (which extracts the 3 JSON files), then run controller function to import into Eloquent MODEL/DB (SQL).

Is this what is possible with this JS script?

**Comment by Zero2Cool** [comment]
You can access the JSON file via HTTP. 
For example, the teamstandings would be this and it gives you a collection of objects to loop through.

https://dugan-760bc.firebaseio.com/data/ps3/218182/standings/teamStandingInfoList/.json

Does that help?

**Comment by furious-bez** [comment]
Ok, sounds like a plan... now to get this going this weekend.  Thanks for the assistance.  Let me know when you would like additional help to get player portraits up and running.

**Comment by Zero2Cool** [comment]
When  I saw the portraits on your screen shot it and after I submitted my question, I was curious if they were on the EA site and sure enough. I think I have it. I just have to figure out how I want the Player Profile page to look! haha. http://kevinduganjr.com/profile?id=544606557

**Comment by furious-bez** [comment]
Nice, I will be completing the player profile page next week.  I started out with a more customized 
![pcard-back](https://user-images.githubusercontent.com/1278361/29886354-9fc3e28e-8d6e-11e7-97f0-7c416b31f0a9.PNG)
method first.

![pcard-front](https://user-images.githubusercontent.com/1278361/29886355-a36f4fe0-8d6e-11e7-8894-70b460e435be.PNG)
![Uploading pcard-back.PNG…]()

**Comment by TopL0ader** [comment]
@Zero2Cool @furious-bez

Morning, 

I too have created a laravel eloquent project using mysql database.

I have the pages and can bring the content in by read and show but I have to manually place the json data taken from the url that corresponds into mysql. 

Can I query a couple of things?

1) how is your mysql tables constructed?
1a) is it by a league row -> data? 

2) having searched for hours and to no success how can I get the json data by url, loop - > create/update the mysql database)

Assitance would be greatly appreciated
