### ISSUE TITLE
Database not receiving data

### ISSUE THREAD

**Issue by JoxWunderwaffe** [birdwell/Madden-Companion-Exporter#8]
I fixed a few minor issues within app.js that were causing crashing in heroku but now that has been resolved. If I've reading the logs correctly the app is receiving the data correctly. However, none of that data is being received by firebase. I checked all my firebase information and it is correct. I even opened the firebase database up to public read/write in hopes it was an authorization issue. Went through the firebase admin API docs and switched a few entries from const to var to match their examples and still nothing.

If you get a chance I'd love if you could look at my repo.

Thanks man

**Comment by Zero2Cool** [comment]
What data was not being pushed to Firebase?

**Comment by Zero2Cool** [comment]
Hey @JoxWunderwaffe I created a Pull Request for you repo.
